In [1]:
import numpy as np

arr = np.array([1,2,3,4,5])

In [2]:
print(arr)

[1 2 3 4 5]


In [3]:
arr3D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr3D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
arrNew = np.arange(10)
print(arrNew)
arrNew = np.arange(2,10,2)
print(arrNew)

[0 1 2 3 4 5 6 7 8 9]
[2 4 6 8]


In [23]:
arr = np.arange(8)
reshaped_arr = arr.reshape(2,4)
print(reshaped_arr)

[[0 1 2 3]
 [4 5 6 7]]


In [22]:
reshaped_arr = arr.reshape(2,2,2)
print(reshaped_arr)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [24]:
 ## important
arr = np.array([[1,2],[3,4]])
flattened = arr.flatten()
print(flattened)

[1 2 3 4]


In [28]:
_2darr = np.array([[1,2,3],[4,5,6]])
print(_2darr.sum())
print(np.sum(_2darr,axis=0)) ## column vise sum

21
[5 7 9]
